_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.19
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 16
beta:
    value: 1
epochs:
    value: 50
lr:
    value: 0.0001
seed:
    value: 42
